-- 清空旧数据
TRUNCATE TABLE code_regulations RESTART IDENTITY CASCADE;

-- 插入规范知识库（册）
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 55037-2022', '建筑防火通用规范', '建筑', '全部通用', '现行', '所有项目必选');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50016-2014（2018 版）', '建筑设计防火规范', '建筑', '住宅、公建、厂房、地下车库', '现行', '所有项目必选');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 55031-2022', '民用建筑通用规范', '建筑', '全部通用', '现行', '所有项目必选');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50352-2019', '民用建筑设计统一标准', '建筑', '全部通用', '现行', '所有项目必选');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50099-2011', '中小学校设计规范', '建筑', '中小学校、幼儿园', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 51039-2014', '综合医院建筑设计规范', '建筑', '医院、康养', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50010-2010（2015 版）', '混凝土结构设计规范', '结构', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50017-2017', '钢结构设计标准', '结构', '厂房、会展、大跨度公建', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50011-2010（2016 版）', '建筑抗震设计规范', '结构', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50009-2012', '建筑结构荷载规范', '结构', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50015-2019', '建筑给水排水设计标准', '给排水', '住宅、普通公建', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50974-2014', '消防给水及消火栓系统技术规范', '给排水', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50038-2014', '人民防空地下室设计规范', '给排水', '地下人防、地下车库', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50242-2002', '建筑给水排水及采暖工程施工质量验收规范', '给排水', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50736-2012', '民用建筑供暖通风与空气调节设计规范', '暖通', '住宅、办公、商业', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50067-2014', '汽车库、修车库、停车场设计防火规范', '暖通', '地下车库、机械停车楼', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50155-2015', '供暖通风与空气调节术语标准', '暖通', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 51245-2017', '工业建筑供暖通风与空气调节设计规范', '暖通', '厂房、生产车间', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 51348-2019', '民用建筑电气设计标准', '电气', '住宅、办公、商业、医院', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50052-2009', '供配电系统设计规范', '电气', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50054-2011', '低压配电设计规范', '电气', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50174-2017', '数据中心设计规范', '电气', '数据机房、算力中心、产业园', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50763-2012', '无障碍设计规范', '建筑', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50034-2013', '建筑照明设计标准', '建筑', '全部通用', '已废止', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 50082-2009', '普通混凝土长期性能和耐久性能试验方法标准', '结构', '全部通用', '已废止', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50500-2013', '建设工程工程量清单计价规范', '建筑', '全部通用', '已废止', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 55036-2022', '消防设施通用规范', '设备/电气', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50222-2017', '建筑内部装修设计防火规范', '建筑', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50084-2017', '自动喷水灭火系统设计规范', '设备', '设有自动喷淋的建筑', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50116-2013', '火灾自动报警系统设计规范', '电气', '设有火灾报警的建筑', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 55019-2021', '建筑与市政工程无障碍通用规范', '建筑', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50038-2005（2023年版）', '人民防空地下室设计规范', '建筑/结构/设备', '人防地下室', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50098-2009', '人民防空工程设计防火规范', '建筑/设备', '人防工程', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 50378-2019（2024年版）', '绿色建筑评价标准', '综合/全专业', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('JGJ/T 229-2010', '民用建筑绿色设计规范', '综合/全专业', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 51129-2017', '装配式建筑评价标准', '综合/结构', '装配式建筑', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('JGJ/T 494-2022', '装配式住宅设计选型标准', '建筑/结构', '装配式住宅', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 45393.1-2025', '信息技术 建筑信息模型（BIM）软件 第1部分：通用要求', '综合/全专业', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 45393.3-2025', '信息技术 建筑信息模型（BIM）软件 第3部分：模型视图定义', '综合/全专业', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50981-2014', '建筑机电工程抗震设计规范', '设备/电气/暖通', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50011-2010（2016年版）', '建筑抗震设计规范', '结构', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB/T 51345-2018', '海绵城市建设评价标准', '给排水/景观', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50400-2016', '建筑与小区雨水控制及利用工程技术规范', '给排水', '全部通用', '现行', '');
INSERT INTO code_regulations (code_number, code_name, applicable_major, applicable_building_type, status, remark) VALUES ('GB 50014-2021', '室外排水设计规范', '给排水', '室外排水工程', '现行', '');

-- 清空历史问题库
TRUNCATE TABLE history_issues RESTART IDENTITY CASCADE;

-- 插入历史问题库
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '学校', '小学单面布房教学用房疏散走道净宽仅 1.1m，宽度不达标', 'GB 50099-2011 8.2.2，中小学校单面走道最小净宽 1.8m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '学校', '幼儿园活动室疏散门向内开启，不符合疏散开启方向要求', 'GB 55037-2022 6.4.11，所有疏散门必须向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散距离超限', '学校', '中学普通教室至安全出口直线疏散距离 23m，超出规范限值', 'GB 50099-2011 表 8.2.3，教学用房至出口距离不应大于 20m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '学校', '寄宿制学校宿舍防火分区面积超 2000㎡，未增设防火分隔', 'GB 50016-2014（2018 版）5.3.4，多层宿舍防火分区最大 1500㎡');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置封闭楼梯间', '住宅', '教学楼仅设置普通敞开楼梯，未按要求采用封闭楼梯间', 'GB 50099-2011 8.2.1，四层及以上中小学教学楼应设封闭楼梯间');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '住宅', '高层住宅套内疏散走道净宽仅 0.9m，不满足规范最小宽度要求', 'GB 50096-2011 5.5.3，住宅套内走道最小净宽不宜小于 1.0m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '住宅', '住宅地下储藏室疏散门向内开启，火灾时无法向外推开疏散', 'GB 55037-2022 6.4.11，疏散门均应向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置封闭楼梯间', '住宅', '二类高层住宅仅设置敞开楼梯，未按规范配置封闭楼梯间', 'GB 50016-2014（2018 版）5.5.13，二类高层住宅应设封闭楼梯间');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '住宅', '高层住宅商业裙房防火分区面积 1800㎡，超出高层商业 1500㎡上限', 'GB 50016-2014（2018 版）5.3.4，高层商业防火分区最大 1500㎡');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散楼梯净宽不达标', '住宅', '多层洋房单元疏散楼梯梯段净宽仅 1.0m，低于规范 1.1m 限值', 'GB 50016-2014（2018 版）表 5.5.21，多层住宅楼梯最小净宽 1.1m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '车库隔墙防火性能不足', '住宅', '住宅与地下车库连通位置仅普通隔墙，未设置 2h 防火隔墙 + 甲级防火门', 'GB 50067-2014 5.2.4，车库与住宅分隔耐火极限不低于 2.00h');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '设备井检修门防火门级别不达标', '住宅', '洋房设备井检修门采用普通木门，未选用乙级防火门封堵洞口', 'GB 50016-2014（2018 版）6.2.7，管道井检修门应为乙级防火门');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道地面应急照明照度不达标', '住宅', '保障房疏散走道地面应急照明实测照度 0.8lx，未达到 1.0lx 最低标准', 'GB 55037-2022 10.1.2，疏散走道地面最低水平照度≥1.0lx');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散楼梯缺少屋面疏散逃生通道', '住宅', '住宅屋面疏散楼梯未直通屋面，缺少屋面疏散逃生通道', 'GB 50016-2014（2018 版）5.5.27，高层住宅楼梯宜直通屋面');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散指示标志间距超限', '住宅', '保障房疏散走道内疏散指示标志间距 12m，超过 10m 布置要求', 'GB 55037-2022 10.1.5，走道疏散指示灯具间距不应大于 10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '学校', '小学教学楼三层内走道净宽仅 1.2m，小于中小学校走道最小净宽 1.8m 的要求', 'GB 50099-2011 8.2.2，中小学校教学用房走道最小净宽不应小于 1.8m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '学校', '幼儿园活动室安全出口门采用内开形式，火灾时无法快速向外疏散', 'GB 55037-2022 6.4.11，疏散门必须向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散距离超限', '学校', '中学普通教室最远点至最近安全出口的直线距离为 22m，超过规范 20m 的限值', 'GB 50099-2011 8.2.3，教学用房内任一点至最近安全出口的距离不应大于 20m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置排烟设施', '学校', '学校风雨操场未设置独立的机械排烟系统，内走道长度超 20m 无排烟设施', 'GB 50016-2014（2018 版）8.5.3，公共建筑内走道长度超过 20m 时应设排烟设施');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '无障碍坡道坡度超标', '学校', '教学楼一层无障碍坡道坡度 1:10，不满足无障碍坡度不大于 1:12 的要求', 'GB 55019-2021 3.4.1，无障碍坡道坡度不应大于 1:12');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '住宅', '高层住宅标准层疏散走道净宽 0.95m，低于住宅疏散走道最小净宽 1.0m 的规定', 'GB 50096-2011 5.5.3，住宅疏散走道最小净宽不应小于 1.0m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '住宅', '住宅地下自行车库疏散门采用内开门，不符合疏散门向外开启的强制要求', 'GB 55037-2022 6.4.11，疏散门应向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '住宅', '二类高层住宅一个防火分区建筑面积为 1600m²，超过规范最大允许 1500m² 的限值', 'GB 50016-2014（2018 版）5.3.4，高层建筑防火分区最大允许建筑面积为 1500m²');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置消防软管卷盘', '住宅', '住宅楼梯间前室未设置消防软管卷盘，不符合高层住宅消防设施配置要求', 'GB 50016-2014（2018 版）8.2.4，高层住宅应设置消防软管卷盘');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '应急照明照度不足', '住宅', '住宅户内消防应急照明灯具照度仅为 0.5lx，低于疏散走道最低照度 1.0lx 的要求', 'GB 51309-2018 3.2.5，住宅疏散走道地面最低水平照度不应低于 1.0lx');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置封闭楼梯间', '学校', '教学楼四层及以上未设置封闭楼梯间，仅设敞开楼梯', 'GB 50099-2011 8.2.1，四层及以上中小学教学楼应设封闭楼梯间');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '学校', '教学楼一层疏散走道净宽1.2m，不满足最小净宽1.4m的要求', 'GB 50099-2011 8.2.3，中小学教学楼疏散走道最小净宽不应小于1.40m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散指示标志间距超限', '学校', '教学楼内疏散指示标志间距18m，超过规范10m的布置要求', 'GB 55037-2022 10.1.5，疏散指示灯具间距不应大于10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '楼梯净宽不达标', '学校', '小学教学楼楼梯间净宽1.0m，低于规范1.1m的限值', 'GB 50099-2011 8.2.2，中小学楼梯最小净宽不应小于1.10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防护栏杆高度不足', '学校', '教学楼二层及以上外廊防护栏杆高度0.90m，低于1.10m的强制要求', 'GB 55031-2022 6.2.3，临空处防护栏杆高度不应小于1.10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '学校', '教学楼一层疏散门向内开启，火灾时无法向外推开', 'GB 55037-2022 6.4.11，疏散门应向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '教室采光系数不达标', '学校', '普通教室采光系数1.5%，不满足中小学教室顶部采光系数不低于2.0%的要求', 'GB 50099-2011 9.1.2，普通教室采光系数不应低于2.0%');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '应急照明照度不足', '学校', '教学楼内消防应急照明灯具照度0.8lx，低于疏散走道最低1.0lx的要求', 'GB 51309-2018 2.5，疏散走道地面最低水平照度不应低于1.0lx');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置机械排风系统', '学校', '教学楼内化学实验室未设置独立的机械排风系统', 'GB 50099-2011 10.3.4，化学实验室应设置独立的机械排风系统');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '学校', '教学楼建筑外墙防火分区面积1800㎡，超出高层建筑1500㎡的限值', 'GB 50016-2014 (2018) 5.3.4，高层建筑防火分区最大允许建筑面积为1500㎡');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防护栏杆高度不足', '学校', '小学教学楼二层及以上外廊防护栏杆高度0.95m，低于1.10m的强制要求', 'GB 55031-2022 6.2.3，临空处防护栏杆高度不应小于1.10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置封闭楼梯间', '学校', '教学楼四层及以上仅设敞开楼梯，未按要求设置封闭楼梯间', 'GB 50099-2011 8.2.1，四层及以上中小学教学楼应设封闭楼梯间');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散走道宽度不达标', '学校', '教学楼内主要疏散走道净宽1.1m，不满足中小学最小净宽1.4m的要求', 'GB 50099-2011 8.2.3，中小学教学楼疏散走道最小净宽不应小于1.40m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '学校', '高层综合教学楼建筑防火分区面积1700㎡，超出高层建筑1500㎡的上限', 'GB 50016-2014 (2018) 5.3.4，高层建筑防火分区最大允许建筑面积为1500㎡');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防护栏杆高度不足', '学校', '教学楼三层连廊及天井周边防护栏杆高度0.90m，低于1.10m的规范限值', 'GB 55031-2022 6.2.3，临空处防护栏杆高度不应小于1.10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门开启方向反向', '学校', '教学楼地下车库与主楼连通处疏散门向内开启，不符合疏散门向外开启的强制性要求', 'GB 55037-2022 6.4.11，疏散门应向疏散方向开启');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '未设置封闭楼梯间', '学校', '小学教学楼四层及以上仅设敞开楼梯间，未设置封闭楼梯间', 'GB 50099-2011 8.2.1，四层及以上中小学教学楼应设封闭楼梯间');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防火分区面积超限', '学校', '高层教学楼一至三层组合防火分区面积1850㎡，超过高层建筑1500㎡的限值', 'GB 50016-2014 (2018) 5.3.4，高层建筑防火分区最大允许建筑面积为1500㎡');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '防护栏杆高度不足', '学校', '幼儿园二层室外活动平台防护栏杆高度0.85m，远低于1.10m的强制要求', 'GB 55031-2022 6.2.3，临空处防护栏杆高度不应小于1.10m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('建筑专业', '疏散门净宽不达标', '学校', '教学楼一层通向室外的疏散门净宽1.2m，低于中小学疏散门最小净宽1.4m的规定', 'GB 50099-2011 8.2.4，中小学疏散门最小净宽不应小于1.40m');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '高层剪力墙加强区竖向分布筋配筋率不达标', '住宅', '高层剪力墙底部加强区竖向分布筋配筋率仅 0.20%，不满足抗震最小配筋要求', 'GB 50010-2010 (2015 版) 11.7.17，7 度抗震剪力墙底部加强区最小配筋率 0.30%');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '未设置抗震伸缩后浇带', '住宅', '主楼与地下车库相连位置未设置抗震伸缩后浇带，未考虑不均匀沉降', 'GB 50011-2010 (2016 版) 3.4.10，主楼与裙 / 车库交界应设沉降后浇带');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '高层连梁未配置交叉暗撑', '住宅', '高层连梁跨高比小于 2.5，未按要求配置交叉暗撑', 'GB 50010-2010 (2015 版) 11.7.11，跨高比≤2.5 连梁宜设交叉钢筋暗撑');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '顶部未配套构造拉结筋', '住宅', '洋房砌体填充墙顶部未设置斜砌顶紧，未配套构造拉结筋', 'GB 50003-2011 6.3.4，填充墙顶部斜砌、全长贯通拉结筋');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '楼梯平台梁未设置混凝土构造柱承托', '住宅', '多层洋房楼梯平台梁支承在填充墙上，未设置混凝土构造柱承托', 'GB 50011-2010 (2016 版) 13.3.4，梁下墙体应增设构造柱');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '屋面悬挑阳台根部未设置抗扭附加钢筋', '住宅', '屋面悬挑阳台根部未设置抗扭附加钢筋，未满足倾覆验算配筋', 'GB 50009-2012 5.5.1，悬挑构件根部增设抗扭附加筋');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '住宅分户楼板最小厚度不足 ', '住宅', '保障房楼板厚度仅 90mm，住宅分户楼板最小厚度不足 100mm', 'GB 50010-2010 (2015 版) 3.6.3，住宅分户楼板厚度不宜小于 100mm');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '楼梯间四角未设置抗震构造柱', '住宅', '楼梯间四角未设置抗震构造柱，不满足多层砌体抗震构造要求', 'GB 50011-2010 (2016 版) 7.3.1，楼梯四角必须设置构造柱');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '外墙门窗洞口两侧未设置 墙体拉结筋', '住宅', '外墙门窗洞口两侧未设置长度≥1000mm 墙体拉结筋', 'GB 50011-2010 (2016 版) 13.3.2，洞口两侧拉结筋伸入墙体≥1000mm');
INSERT INTO history_issues (major, issue_summary, building_type, issue_description, requirement) VALUES ('结构专业', '高层框架柱箍筋加密区长度小于柱高限值', '住宅', '高层框架柱箍筋加密区长度仅 500mm，小于规范 1.5 倍柱高限值', 'GB 50011-2010 (2016 版) 6.3.7，柱端加密区长度取柱长边、1/6 柱高二者大值');
