const fs = require("fs");
const path = require("path");
const L = [];
function a(s) { L.push(s); }

a("");
a("function ReviewPanel({ projectInfo, projectId }) {");
a("  const [editableInfo, setEditableInfo] = useState(null);");
a("  const [confirmed, setConfirmed] = useState(false);");
a("  const [generating, setGenerating] = useState(false);");
a("  const [reviewResult, setReviewResult] = useState(null);");
a("  const [showAllRegulations, setShowAllRegulations] = useState(false);");
a("  const [hasFile, setHasFile] = useState(!!projectInfo);");
a("  const [file, setFile] = useState(null);");
a("  const [uploading, setUploading] = useState(false);");
a("  const fileInputRef = useRef(null);");
a("");
a("  useEffect(() => {");
a("    if (projectInfo) {");
a("      setEditableInfo(JSON.parse(JSON.stringify(projectInfo)));");
a("      setHasFile(true);");
a("    }");
a("  }, [projectInfo]);");
a("");
a("  const handleInfoChange = (section, key, value) => {");
a("    setEditableInfo((prev) => {");
a("      const next = JSON.parse(JSON.stringify(prev));");
a("      next[section][key] = value || null;");
a("      return next;");
a("    });");
a("  };");
a("");
a("  const handleUploadFile = async () => {");
a("    if (!file) return;");
a("    setUploading(true);");
a("    try {");
a("      const formData = new FormData();");
a("      formData.append(\"name\", \"项目文件更新\");");
a("      formData.append(\"file\", file);");
a("      formData.append(\"project_id\", projectId);");
a("      const res = await fetch(\"/api/projects\", { method: \"POST\", body: formData });");
a("      const json = await res.json();");
a("      const info = json.data?.project_info || { project_info: {}, special_designs: {} };");
a("      setEditableInfo(info);");
a("      setHasFile(true);");
a("      sessionStorage.setItem(\"project_\" + projectId, JSON.stringify({ name: json.data?.project_name || \"未命名项目\", project_info: info }));");
a("    } catch (e) { console.error(\"上传失败\", e); }");
a("    finally { setUploading(false); }");
a("  };");
a("");
a("  const handleConfirmGenerate = async () => {");
a("    setGenerating(true);");
a("    try {");
a("      const res = await fetch(\"/api/review/generate\", {");
a("        method: \"POST\","); 
a("        headers: { \"Content-Type\": \"application/json\" },");
a("        body: JSON.stringify({ project_info: editableInfo?.project_info || {}, special_designs: editableInfo?.special_designs || {} }),");
a("      });");
a("      const json = await res.json();");
a("      if (json.success) { setReviewResult(json.data); setConfirmed(true); }");
a("      else { alert(\"生成审图清单失败: \" + (json.error || \"未知错误\")); }");
a("    } catch (e) { alert(\"生成审图清单失败，请稍后重试\"); }");
a("    finally { setGenerating(false); }");
a("  };");
a("");
a("  if (!editableInfo && !hasFile) {");
a("    return (");
a("      <div className=\"space-y-6\">");
a("        <form onSubmit={(e) => { e.preventDefault(); handleUploadFile(); }} className=\"space-y-6\">");
a("          <div onClick={() => fileInputRef.current?.click()} className=\"border-2 border-dashed border-gray-200 rounded-lg p-12 text-center cursor-pointer hover:border-blue-300 transition-colors\">");
a("            <input ref={fileInputRef} type=\"file\" className=\"hidden\" accept=\".pdf,.docx,.doc,.txt\"");
a("              onChange={(e) => { const f = e.target.files?.[0]; if (f) setFile(f); }} />");
a("            <CloudUpload className=\"w-12 h-12 text-blue-600 mx-auto mb-3\" />");
a("            <p className=\"text-sm text-gray-600\">点击或拖拽上传项目设计说明</p>");
a("            <p className=\"text-xs text-gray-400 mt-1\">支持 PDF、DOCX、DOC、TXT 格式</p>");
a("          </div>");
a("          {file && (");
a("            <div className=\"flex items-center gap-2 text-sm text-gray-700 bg-gray-50 rounded-lg px-4 py-2\">");
a("              <span>{file.name}</span>");
a("              <button type=\"button\" onClick={() => setFile(null)} className=\"ml-auto text-gray-400 hover:text-gray-600\"><X className=\"w-4 h-4\" /></button>");
a("            </div>");
a("          )}");
a("          <Button type=\"submit\" disabled={!file || uploading} className=\"w-full h-11 bg-blue-600 hover:bg-blue-700 text-white\">{uploading ? \"提交中...\" : \"确认提交\"}</Button>");
a("        </form>");
a("      </div>");
a("    );");
a("  }");
a("");
a("  const projectData = editableInfo?.project_info || {};");
a("  if (!projectData[\"审图专业\"]) { projectData[\"审图专业\"] = \"建筑专业\"; }");
a("  const specialData = editableInfo?.special_designs || {};");
a("  const projectKeys = Object.keys(projectData).filter(k => k !== \"审图专业\").concat(\"审图专业\");");
a("  const specialKeys = Object.keys(specialData);");
a("");

// Now the confirmed display
const out2 = path.join("D:\\codex-project\\shenxiaozu-demo\\tools\\part2.txt");
fs.writeFileSync(out2, L.join("\n"), "utf-8");
console.log("part2 done");