const fs = require("fs");
const path = require("path");
const L = [];
function a(s) { L.push(s); }

a("\"use client\";");
a("");
a("import { Suspense } from \"react\";");
a("import { useSearchParams, useRouter } from \"next/navigation\";");
a("import Link from \"next/link\";");
a("import { useState, useEffect, useRef } from \"react\";");
a("import { Button } from \"@/components/ui/button\";");
a("import { PlusCircle, CloudUpload, X } from \"lucide-react\";");
a("import { supabase } from \"@/lib/supabase/client\";");
a("");
a("type Project = {");
a("  id: string;");
a("  name: string;");
a("  description: string | null;");
a("  created_at: string;");
a("  project_info: any | null;");
a("};");
a("");
a("const tabs = [");
a("  { key: \"code\", label: \"规范问答\" },");
a("  { key: \"review\", label: \"审图规划\" },");
a("  { key: \"report\", label: \"报告生成\" },");
a("  { key: \"compare\", label: \"报告对比\" },");
a("  { key: \"issues\", label: \"问题追踪\" },");
a("];");
a("");
a("function ProjectsPageContent() {");
a("  const searchParams = useSearchParams();");
a("  const router = useRouter();");
a("  const projectId = searchParams.get(\"id\");");
a("  const tabParam = searchParams.get(\"tab\");");
a("  const [activeTab, setActiveTab] = useState(tabParam || \"review\");");
a("  const [project, setProject] = useState(null);");
a("  const [loading, setLoading] = useState(true);");
a("");
a("  useEffect(() => {");
a("    if (!projectId) { setLoading(false); return; }");
a("    const fetchProject = async () => {");
a("      try {");
a("        const cached = sessionStorage.getItem(`project_${projectId}`);");
a("        if (cached) {");
a("          try {");
a("            const parsed = JSON.parse(cached);");
a("            setProject({ id: projectId, name: parsed.name || \"未命名项目\", description: null, created_at: new Date().toISOString(), project_info: parsed.project_info || null });");
a("            sessionStorage.removeItem(`project_${projectId}`);");
a("            setLoading(false); return;");
a("          } catch(e) {}");
a("        }");
a("        const res = await fetch(`/api/project-item?id=${projectId}`);");
a("        const json = await res.json();");
a("        if (json.success && json.data) {");
a("          setProject(json.data);");
a("        } else { console.error(\"获取项目失败:\", json.error); }");
a("      } catch (e) { console.error(\"获取项目失败\", e); }");
a("      finally { setLoading(false); }");
a("    };");
a("    fetchProject();");
a("  }, [projectId]);");
a("");
a("  const handleTabChange = (key) => {");
a("    setActiveTab(key);");
a("    const params = new URLSearchParams(searchParams);");
a("    params.set(\"tab\", key);");
a("    router.replace(`/projects?${params.toString()}`, { scroll: false });");
a("  };");
a("");
a("  if (!projectId) {");
a("    return (");
a("      <div className=\"flex flex-col items-center justify-center h-full py-20 text-center\">");
a("        <h2 className=\"text-xl font-bold text-gray-900 mb-2\">暂无项目</h2>");
a("        <p className=\"text-sm text-gray-500 mb-6\">您还没有创建任何项目，点击下方按钮开始</p>");
a("        <Link href=\"/projects/new\">");
a("          <Button className=\"bg-blue-600 hover:bg-blue-700 text-white\">");
a("            <PlusCircle className=\"w-4 h-4 mr-2\" /> 新建项目");
a("          </Button>");
a("        </Link>");
a("      </div>");
a("    );");
a("  }");
a("");
a("  if (loading) {");
a("    return <div className=\"text-center py-20 text-gray-500\">加载中...</div>;");
a("  }");
a("");
a("  return (");
a("    <div className=\"space-y-6\">");
a("      <div className=\"flex items-center justify-between\">");
a("        <div>");
a("          <h1 className=\"text-xl font-bold text-gray-900\">{project?.name || \"未命名项目\"}</h1>");
a("          <p className=\"text-sm text-gray-500 mt-1\">创建时间：{project?.created_at ? new Date(project.created_at).toLocaleDateString() : \"--\"}</p>");
a("        </div>");
a("      </div>");
a("      <div className=\"border-b border-gray-200\">");
a("        <nav className=\"flex gap-8\">");
a("          {tabs.map((tab) => (");
a("            <button key={tab.key} onClick={() => handleTabChange(tab.key)}");
a("              className={`pb-3 text-sm font-medium border-b-2 transition-colors ${activeTab === tab.key ? \"border-blue-600 text-blue-600\" : \"border-transparent text-gray-500 hover:text-gray-700\"}`}>{tab.label}</button>");
a("          ))}");
a("        </nav>");
a("      </div>");
a("      <div className=\"bg-white rounded-xl border border-gray-200 p-8 min-h-[300px]\">");
a("        {activeTab === \"review\" && <ReviewPanel projectInfo={project?.project_info} projectId={projectId || \"\"} />}");
a("        {activeTab === \"code\" && <div className=\"text-center text-gray-500\"><p className=\"text-base font-medium mb-2\">规范问答</p><p className=\"text-sm\">功能开发中...</p></div>}");
a("        {activeTab === \"report\" && <div className=\"text-center text-gray-500\"><p className=\"text-base font-medium mb-2\">报告生成</p><p className=\"text-sm\">功能开发中...</p></div>}");
a("        {activeTab === \"compare\" && <div className=\"text-center text-gray-500\"><p className=\"text-base font-medium mb-2\">报告对比</p><p className=\"text-sm\">功能开发中...</p></div>}");
a("        {activeTab === \"issues\" && <div className=\"text-center text-gray-500\"><p className=\"text-base font-medium mb-2\">问题追踪</p><p className=\"text-sm\">功能开发中...</p></div>}");
a("      </div>");
a("    </div>");
a("  );");
a("}");
a("");

const out = path.join("D:\\codex-project\\shenxiaozu-demo\\tools\\page-output.js");
fs.writeFileSync(out, L.join("\n"), "utf-8");
console.log("part1 done");